# Generated by Django 5.2.1 on 2025-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
