# Generated by Django 5.2.1 on 2025-06-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
