# Generated by Django 5.2.1 on 2025-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
